name: Building assets

on: [push, pull_request]

jobs:
  build-assets:

    strategy:
      matrix:
        node-version: [15.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: public/template/package-lock.json
      - run: npm ci
        working-directory: ./public/template
      - run: npm run release
        working-directory: ./public/template
