name: Validate

on: [push, pull_request]

jobs:
  validate-json:
    name: 'validate json'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate language file
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./lang.schema.json
          INPUT_JSONS: ./lang.json
      - name: Validate sources file
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./sources.schema.json
          INPUT_JSONS: ./sources.dist.json
  phpcs:
    name: 'phpcs + compat checker'
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    steps:
      -   uses: actions/checkout@v4

      -   name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-version }}
            extensions: pdo, pdo_mysql, zip, mysqli, gd

      -   name: Install dependencies
          run: composer install --no-progress --prefer-dist --optimize-autoloader

      -   name: phpcs
          run: composer run phpcs -- --runtime-set testVersion ${{ matrix.php-version }}
